#!/usr/bin/env bash
###############################################################################
# install_mediamtx.sh -- install MediaMTX as the WebRTC gateway for the camera.
#
# MediaMTX receives the camera's H.264 over RTSP (pushed by
# camera_stream_server.py --rtsp-url) and re-serves it to browsers as WebRTC
# (sub-second latency). Single static binary, no other deps.
#
# Re-running is safe: it re-downloads only if the version changed.
#
# Usage:
#   ./camera_stream/install_mediamtx.sh [options]
#
# Options:
#   --version VER   MediaMTX release tag          (default v1.19.3)
#   --path NAME     RTSP/WebRTC path for the camera (default cam)
#   --prefix DIR    install location              (default /opt/mediamtx)
#   --no-service    install files but do not install/start systemd
#   -h | --help     show this help
#
# After install:
#   WebRTC viewer : http://<orangepi-ip>:8889/<path>
#   RTSP          : rtsp://<orangepi-ip>:8554/<path>
###############################################################################
set -euo pipefail

VERSION="${VERSION:-v1.19.3}"
PATH_NAME="${PATH_NAME:-cam}"
PREFIX="${PREFIX:-/opt/mediamtx}"
INSTALL_SERVICE=1
SERVICE_NAME="mediamtx.service"
UNIT_DST="/etc/systemd/system/$SERVICE_NAME"

log()  { printf '\033[1;34m[mediamtx]\033[0m %s\n' "$*"; }
ok()   { printf '\033[1;32m[ ok ]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[warn ]\033[0m %s\n' "$*"; }
die()  { printf '\033[1;31m[error]\033[0m %s\n' "$*" >&2; exit 1; }
if command -v sudo >/dev/null 2>&1; then SUDO=sudo; else SUDO=; fi

while [[ $# -gt 0 ]]; do
  case "$1" in
    --version)    VERSION="$2"; shift 2 ;;
    --path)       PATH_NAME="$2"; shift 2 ;;
    --prefix)     PREFIX="$2"; shift 2 ;;
    --no-service) INSTALL_SERVICE=0; shift ;;
    -h|--help)    sed -n '2,30p' "${BASH_SOURCE[0]}"; exit 0 ;;
    *) die "unknown option: $1 (use --help)" ;;
  esac
done

log "MediaMTX installer  ($VERSION)  path=/$PATH_NAME  prefix=$PREFIX"

# ---- pick the right tarball for this CPU --------------------------------------
ARCH="$(uname -m)"
case "$ARCH" in
  x86_64|amd64)        MTX_ARCH="linux_amd64" ;;
  aarch64|arm64)       MTX_ARCH="linux_arm64" ;;   # Orange Pi 3B (RK3566)
  armv7l|armv7|armhf)  MTX_ARCH="linux_armv7" ;;
  *) die "unsupported arch: $ARCH" ;;
esac
TARBALL="mediamtx_${VERSION}_${MTX_ARCH}.tar.gz"
URL="https://github.com/bluenviron/mediamtx/releases/download/${VERSION}/${TARBALL}"

# ---- 1. download + extract the binary -----------------------------------------
log "[1/3] Downloading $TARBALL"
$SUDO mkdir -p "$PREFIX"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
if command -v curl >/dev/null 2>&1; then
  curl -fsSL "$URL" -o "$TMP/mtx.tar.gz" || die "download failed: $URL"
else
  wget -q "$URL" -O "$TMP/mtx.tar.gz" || die "download failed: $URL"
fi
tar -xzf "$TMP/mtx.tar.gz" -C "$TMP"
[[ -f "$TMP/mediamtx" ]] || die "mediamtx binary not found in tarball"
$SUDO install -m 0755 "$TMP/mediamtx" "$PREFIX/mediamtx"
ok "binary -> $PREFIX/mediamtx"

# ---- 2. minimal config: RTSP in, WebRTC out ------------------------------------
log "[2/3] Writing config ($PREFIX/mediamtx.yml)"
# Only enable what we use: RTSP (8554, the ffmpeg push target) and WebRTC
# (8889 for the browser page/API, 8189/udp for the media). Everything else off.
$SUDO tee "$PREFIX/mediamtx.yml" > /dev/null <<CFG
# MediaMTX config for the camera WebRTC gateway (generated by install_mediamtx.sh)
logLevel: info
rtsp: yes
webrtc: yes
hls: no
rtmp: no
srt: no
api: no
metrics: no
paths:
  ${PATH_NAME}:
    # Accept the H.264 pushed by camera_stream_server.py --rtsp-url and
    # re-serve it to browsers as WebRTC. No transcoding happens here.
CFG
ok "config written"

# ---- 3. systemd service ---------------------------------------------------------
if [[ "$INSTALL_SERVICE" -eq 1 ]]; then
  log "[3/3] Installing + starting systemd unit ($SERVICE_NAME)"
  UNIT="$(mktemp)"
  cat > "$UNIT" <<UNIT_EOF
[Unit]
Description=MediaMTX WebRTC gateway for the camera
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=$PREFIX/mediamtx $PREFIX/mediamtx.yml
Restart=on-failure
RestartSec=3

[Install]
WantedBy=multi-user.target
UNIT_EOF
  $SUDO cp "$UNIT" "$UNIT_DST"
  rm -f "$UNIT"
  $SUDO systemctl daemon-reload
  $SUDO systemctl enable "$SERVICE_NAME" >/dev/null 2>&1 || true
  $SUDO systemctl restart "$SERVICE_NAME"
  sleep 2
  systemctl is-active --quiet "$SERVICE_NAME" \
    && ok "$SERVICE_NAME is active" \
    || warn "not active yet -- check: journalctl -u $SERVICE_NAME -n 50"
else
  log "[3/3] Skipping systemd (--no-service)"
  log "Run manually: $PREFIX/mediamtx $PREFIX/mediamtx.yml"
fi

IP_ADDR="$(hostname -I 2>/dev/null | awk '{print $1}')"; IP_ADDR="${IP_ADDR:-<orangepi-ip>}"
cat <<EOF

$(printf '\033[1;32m')============ mediamtx install complete ============$(printf '\033[0m')
  WebRTC viewer : http://$IP_ADDR:8889/$PATH_NAME
  RTSP (push)   : rtsp://$IP_ADDR:8554/$PATH_NAME

  Now point the camera daemon at it (H.264 -> WebRTC):
    ./camera_stream/install.sh --input-format h264 \\
        --rtsp-url rtsp://127.0.0.1:8554/$PATH_NAME

  Manage:
    sudo systemctl status $SERVICE_NAME
    journalctl -u $SERVICE_NAME -f
EOF
